[build]
builder = "NIXPACKS"
nixpacksConfigPath = "./nixpacks.build.pnpm.toml"

[deploy]
region = "europe-west4"
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10